[2023-01-05T12:25:47.225+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-05T12:17:22.287490+00:00 [queued]>
[2023-01-05T12:25:47.245+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-05T12:17:22.287490+00:00 [queued]>
[2023-01-05T12:25:47.246+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T12:25:47.247+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 4
[2023-01-05T12:25:47.247+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T12:25:47.309+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard> on 2023-01-05 12:17:22.287490+00:00
[2023-01-05T12:25:47.321+0000] {standard_task_runner.py:55} INFO - Started process 735 to run task
[2023-01-05T12:25:47.330+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uk_accidents_etl_pipeline', 'create_dashboard', 'manual__2023-01-05T12:17:22.287490+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/milestone_3.py', '--cfg-path', '/tmp/tmpte32jzlh']
[2023-01-05T12:25:47.336+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask create_dashboard
[2023-01-05T12:25:47.600+0000] {task_command.py:389} INFO - Running <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-05T12:17:22.287490+00:00 [running]> on host ecc1437a0be2
[2023-01-05T12:25:48.062+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-05T12:17:22.287490+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-05T12:17:22.287490+00:00
[2023-01-05T12:25:48.150+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dashbord.py", line 35, in create_dashboard
    dcc.Graph(figure=plot_missing_values(filename)),
  File "/opt/airflow/dags/dashbord.py", line 11, in plot_missing_values
    data = [(col, df[col].isnull().sum()) for col in df.columns]
AttributeError: 'str' object has no attribute 'columns'
[2023-01-05T12:25:48.196+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=uk_accidents_etl_pipeline, task_id=create_dashboard, execution_date=20230105T121722, start_date=20230105T122547, end_date=20230105T122548
[2023-01-05T12:25:48.409+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 37 for task create_dashboard ('str' object has no attribute 'columns'; 735)
[2023-01-05T12:25:48.463+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-05T12:25:48.626+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
