[2023-01-02T23:55:49.427+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:34:45.102029+00:00 [queued]>
[2023-01-02T23:55:49.484+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:34:45.102029+00:00 [queued]>
[2023-01-02T23:55:49.488+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T23:55:49.492+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-02T23:55:49.494+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T23:55:49.600+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard> on 2023-01-02 23:34:45.102029+00:00
[2023-01-02T23:55:49.623+0000] {standard_task_runner.py:55} INFO - Started process 1381 to run task
[2023-01-02T23:55:49.625+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uk_accidents_etl_pipeline', 'create_dashboard', 'manual__2023-01-02T23:34:45.102029+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/milestone_3.py', '--cfg-path', '/tmp/tmp9qr8_chy']
[2023-01-02T23:55:49.638+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask create_dashboard
[2023-01-02T23:55:49.975+0000] {task_command.py:389} INFO - Running <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:34:45.102029+00:00 [running]> on host 82068c2abeb3
[2023-01-02T23:55:50.478+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T23:34:45.102029+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T23:34:45.102029+00:00
[2023-01-02T23:56:24.218+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-02T23:56:24.218+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-02T23:56:24.232+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-02T23:56:24.232+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-02T23:56:24.234+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.19.0.3:8050
[2023-01-02T23:56:24.235+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-03T00:13:03.626+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-03T00:13:03.637+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1381. PIDs of all processes in the group: [1381]
[2023-01-03T00:13:03.664+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1381
[2023-01-03T00:13:03.694+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-03T00:13:03.783+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dashbord.py", line 69, in create_dashboard
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-03T00:13:03.867+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=uk_accidents_etl_pipeline, task_id=create_dashboard, execution_date=20230102T233445, start_date=20230102T235549, end_date=20230103T001303
[2023-01-03T00:13:04.129+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task create_dashboard (Task received SIGTERM signal; 1381)
[2023-01-03T00:13:04.175+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1381, status='terminated', exitcode=1, started='23:55:49') (1381) terminated with exit code 1
[2023-01-03T00:13:04.176+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-03T00:13:04.226+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-03T00:13:07.145+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
