[2023-01-02T23:47:39.886+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:34:45.102029+00:00 [queued]>
[2023-01-02T23:47:39.918+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:34:45.102029+00:00 [queued]>
[2023-01-02T23:47:39.921+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T23:47:39.930+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-02T23:47:39.933+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T23:47:39.998+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard> on 2023-01-02 23:34:45.102029+00:00
[2023-01-02T23:47:40.011+0000] {standard_task_runner.py:55} INFO - Started process 928 to run task
[2023-01-02T23:47:40.021+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uk_accidents_etl_pipeline', 'create_dashboard', 'manual__2023-01-02T23:34:45.102029+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/milestone_3.py', '--cfg-path', '/tmp/tmp1a3jym4m']
[2023-01-02T23:47:40.031+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask create_dashboard
[2023-01-02T23:47:40.266+0000] {task_command.py:389} INFO - Running <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:34:45.102029+00:00 [running]> on host 82068c2abeb3
[2023-01-02T23:47:40.534+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T23:34:45.102029+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T23:34:45.102029+00:00
[2023-01-02T23:48:03.119+0000] {logging_mixin.py:137} INFO - Dash is running on http://127.0.0.1:8050/
[2023-01-02T23:48:03.119+0000] {dash.py:1968} INFO - Dash is running on http://127.0.0.1:8050/

[2023-01-02T23:48:03.372+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-02T23:48:03.374+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-02T23:48:03.377+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
[2023-01-02T23:48:03.378+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-02T23:50:39.416+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-01-02T23:50:39.423+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 928. PIDs of all processes in the group: [928]
[2023-01-02T23:50:39.424+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 928
[2023-01-02T23:50:39.425+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-02T23:50:39.456+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dashbord.py", line 69, in create_dashboard
    app.run_server(host='0.0.0.0')
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-02T23:50:39.482+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=uk_accidents_etl_pipeline, task_id=create_dashboard, execution_date=20230102T233445, start_date=20230102T234739, end_date=20230102T235039
[2023-01-02T23:50:39.555+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task create_dashboard (Task received SIGTERM signal; 928)
[2023-01-02T23:50:39.600+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=928, status='terminated', exitcode=1, started='23:47:39') (928) terminated with exit code 1
