[2023-01-05T12:09:26.768+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:54:40.991487+00:00 [queued]>
[2023-01-05T12:09:26.791+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:54:40.991487+00:00 [queued]>
[2023-01-05T12:09:26.791+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T12:09:26.793+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 4
[2023-01-05T12:09:26.796+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-05T12:09:26.833+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard> on 2023-01-02 23:54:40.991487+00:00
[2023-01-05T12:09:26.844+0000] {standard_task_runner.py:55} INFO - Started process 237 to run task
[2023-01-05T12:09:26.850+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uk_accidents_etl_pipeline', 'create_dashboard', 'manual__2023-01-02T23:54:40.991487+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/milestone_3.py', '--cfg-path', '/tmp/tmp541v2kiw']
[2023-01-05T12:09:26.854+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask create_dashboard
[2023-01-05T12:09:27.296+0000] {task_command.py:389} INFO - Running <TaskInstance: uk_accidents_etl_pipeline.create_dashboard manual__2023-01-02T23:54:40.991487+00:00 [running]> on host 82068c2abeb3
[2023-01-05T12:09:27.814+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T23:54:40.991487+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T23:54:40.991487+00:00
[2023-01-05T12:09:27.837+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dashbord.py", line 35, in create_dashboard
    dcc.Graph(figure=plot_missing_values(filename)),
  File "/opt/airflow/dags/dashbord.py", line 11, in plot_missing_values
    data = [(col, df[col].isnull().sum()) for col in df.columns]
AttributeError: 'str' object has no attribute 'columns'
[2023-01-05T12:09:27.863+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=uk_accidents_etl_pipeline, task_id=create_dashboard, execution_date=20230102T235440, start_date=20230105T120926, end_date=20230105T120927
[2023-01-05T12:09:27.918+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task create_dashboard ('str' object has no attribute 'columns'; 237)
[2023-01-05T12:09:28.071+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-05T12:09:28.349+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
